export const APP_CONFIG = {
  SCHEDULE: {
    MAX_ACTIVE_SCHEDULES: 10,
    MIN_INTERVAL_HOURS: 2,
  },

  FOOD_LEVEL: {
    LOW_LEVEL_THRESHOLD: 20,
    DAYS_FOR_CONSUMPTION_CALC: 7,
    CONTAINER_CAPACITY_GRAMS: 1000,
  },

  PORTION: {
    MIN_SIZE_GRAMS: 10,
    MAX_SIZE_GRAMS: 500,
  },
} as const;