export enum NotificationType {
    FEEDING_SUCCESS = 'FEEDING_SUCCESS',
    FEEDING_FAILED = 'FEEDING_FAILED',
    LOW_FOOD_LEVEL = 'LOW_FOOD_LEVEL',
    DEVICE_OFFLINE = 'DEVICE_OFFLINE',
    DEVICE_ONLINE = 'DEVICE_ONLINE',
}